### ISSUE TITLE
无法正常配置源

### ISSUE THREAD

**Issue by Frisk-Colin** [sjtug/mirror-requests#372]
执行apt-get update显示如下内容：
Traceback (most recent call last):
  File "/usr/lib/cnf-update-db", line 27, in <module>
    col.create(db)
  File "/usr/share/command-not-found/CommandNotFound/db/creator.py", line 95, in create
    self._fill_commands(con)
  File "/usr/share/command-not-found/CommandNotFound/db/creator.py", line 143, in _fill_commands
    self._parse_single_contents_file(con, f, fp.stdout)
  File "/usr/share/command-not-found/CommandNotFound/db/creator.py", line 282, in _parse_single_contents_file
    priority = component_priorities[component]
KeyError: 'non-free-firmware'

**Comment by truc0** [comment]
你报告的问题似乎与系统中的 command-not-found 组件相关，镜像源目前运作正常。

我对Debian（如果适用）的command-not-found组件了解不深，你可以参考以下链接（由AI生成，注意甄别信息）尝试修复：

https://devv.ai/search?threadId=e65xrk311rsw

**Comment by truc0** [comment]
由于该issue已经一段时间没有回复，该 issue 已被关闭。如果问题仍未解决，欢迎重新开启 issue 或提交新 issue。
